# Generated by Django 5.1.4 on 2024-12-16 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_messagetype_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subcategories', to='app.category'),
        ),
        migrations.DeleteModel(
            name='MessageType',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
