# Generated by Django 5.0.4 on 2024-05-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_productmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='preview_image',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
