# Generated by Django 5.1.4 on 2024-12-15 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('app', '0003_messagetype_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.brand'),
        ),
    ]
